---
title: "impervious_area_lm_plots"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
```

```{r}
#import data, creating categories for open water sites (ow), tidal creek sites (tc), and all sites (all)

scecap_watershed_all <- read.csv("../data/watershed_env_data.csv")
scecap_watershed_ow  <- read.csv("../output/watershed_env_data_openwater.csv")
scecap_watershed_tc  <- read.csv("../output/watershed_env_data_tidalcreek.csv")
impervious <- read.csv("../data/impervious_prct_cover.csv")

#subset impervious data (most recent year, upland cat = 2) 

impervious_subset <- filter(impervious, YEAR == 2011, UPLAND == 2)

#join environmental data with impervious cover

scecap_imperv_join_all <- full_join(scecap_watershed_all, impervious_subset, by = "HUC_ID")
scecap_imperv_join_ow <- full_join(scecap_watershed_ow, impervious_subset, by = "HUC_ID")
scecap_imperv_join_tc <- full_join(scecap_watershed_tc, impervious_subset, by = "HUC_ID")

#remove HUCs w/ less than 3 stations

scecap_imperv_join_all <- filter(scecap_imperv_join_all, NUMBER_STATIONS >2)
scecap_imperv_join_ow <- filter(scecap_imperv_join_ow, NUMBER_STATIONS >2)
scecap_imperv_join_tc <- filter(scecap_imperv_join_tc, NUMBER_STATIONS >2)

#separate data by HUC digit

scecap_imperv_huc08_all <- filter(scecap_imperv_join_all, HUC_DIGITS.x == 8)
scecap_imperv_huc10_all <- filter(scecap_imperv_join_all, HUC_DIGITS.x == 10)
scecap_imperv_huc12_all <- filter(scecap_imperv_join_all, HUC_DIGITS.x == 12)
scecap_imperv_huc14_all <- filter(scecap_imperv_join_all, HUC_DIGITS.x == 14)

scecap_imperv_huc08_ow <- filter(scecap_imperv_join_ow, HUC_DIGITS.x == 8)
scecap_imperv_huc10_ow <- filter(scecap_imperv_join_ow, HUC_DIGITS.x == 10)
scecap_imperv_huc12_ow <- filter(scecap_imperv_join_ow, HUC_DIGITS.x == 12)
scecap_imperv_huc14_ow <- filter(scecap_imperv_join_ow, HUC_DIGITS.x == 14)

scecap_imperv_huc08_tc <- filter(scecap_imperv_join_tc, HUC_DIGITS.x == 8)
scecap_imperv_huc10_tc <- filter(scecap_imperv_join_tc, HUC_DIGITS.x == 10)
scecap_imperv_huc12_tc <- filter(scecap_imperv_join_tc, HUC_DIGITS.x == 12)
scecap_imperv_huc14_tc <- filter(scecap_imperv_join_tc, HUC_DIGITS.x == 14)
```

```{r}
#build function that plots linear model between impervious cover (x) and environmental response (y)

scecap_scatterplot <- function(x) 
  
  {
  for(i in 5:10)  
    {
    lm_xy <- lm((x[,i]) ~ (x[,14]))
    lm_xy_sum <- summary(lm_xy)
    rsqr <- lm_xy_sum$adj.r.squared
    plot((x[,i]) ~ (x[,14]), main = paste("HUC", x[1,3]), xlab = colnames(x[14]), ylab = colnames(x[i]))
    abline(lm_xy, col = 'red')
    legend("topright", bty="n", legend=paste("Adj.R2 =", format(rsqr, digits=4)))
    }
  }

#run function for each watershed category
scecap_scatterplot(scecap_imperv_huc08_all)
scecap_scatterplot(scecap_imperv_huc10_all)
scecap_scatterplot(scecap_imperv_huc12_all)
scecap_scatterplot(scecap_imperv_huc14_all)

scecap_scatterplot(scecap_imperv_huc08_ow)
scecap_scatterplot(scecap_imperv_huc10_ow)
scecap_scatterplot(scecap_imperv_huc12_ow)
scecap_scatterplot(scecap_imperv_huc14_ow)

scecap_scatterplot(scecap_imperv_huc08_tc)
scecap_scatterplot(scecap_imperv_huc10_tc)
scecap_scatterplot(scecap_imperv_huc12_tc)
scecap_scatterplot(scecap_imperv_huc14_tc)
```

