---
title: "trawl species summaries"
date: 3.25.2019
output: html_notebook
---

```{r}
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyverse)

```

```{r}
#import trawl dataset

trawl <- read.csv("../data/trawl_data.csv")

#summarize data by station, counting number of unique species

trawl_summary <- trawl %>% group_by(STATION_ID) %>% summarize(n_distinct(SP_CODE))

#rename columns

names(trawl_summary) <- c("STATION_ID", "SP_RICHNESS")

openwater_trawl <- trawl_summary %>% filter(str_detect(STATION_ID, 'RO'))
tidalcreek_trawl <- trawl_summary %>% filter(str_detect(STATION_ID, 'RT'))

openwater_trawl$SITE_TYPE <- "OpenWater"
tidalcreek_trawl$SITE_TYPE <- "TidalCreek"

trawl_richness <- bind_rows(openwater_trawl, tidalcreek_trawl)

ggplot(data = trawl_richness, aes(x=SITE_TYPE, y=SP_RICHNESS)) + geom_boxplot()


trawl_richness$YEAR <- str_sub(string = trawl_richness$STATION_ID, start = 3, end = 4)
trawl_richness$YEAR <- paste('20', trawl_richness$YEAR, sep = "")

trawl_richness$YEAR <- str_replace(trawl_richness$YEAR, '2099', '1999')

trawl_richness

```

